name: Organization Security Code Scanning
on:
  workflow_call:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  security-events: read

jobs:
  secret-scanning:
    name: Secret Scanning - Betterleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Betterleaks
        uses: un-fao/fao-github-workflows/.github/security/sca/betterleaks@main
        with:
          pr_id: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  sast-scanning:
    name: SAST Scanning - Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Semgrep
        uses: un-fao/fao-github-workflows/.github/security/sca/semgrep@main
        with:
          pr_id: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_threshold: ERROR

  dependabot-scanning:
    name: SCA Scanning - Dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Dependabot Inspector
        uses: un-fao/fao-github-workflows/.github/security/sca/dependabot@main
        with:
          pr_id: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}